language: c

before_install:
    - sudo apt-get update
    - sudo apt-get install byacc automake autoconf build-essential gnupg

script:
    - cd src
    - ./autogen.sh
    - ./configure
    - make
    - sudo make install
