language: c

before_install:
    - sudo apt-get update
    - sudo apt-get install byacc automake autoconf build-essential gnupg telnet whois

script:
    - cd src
    - ./autogen.sh
    - ./configure
    - make
    - sudo make install
    - cd ../tests
    - make test

after_script:
    - sudo rm -rf /tmp/irr /var/spool/irr_database
